Algoritmo "3. VerificaçãoNumPN"

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ester Trindade
// Data atual  : 03/06/2024

Var

   num : inteiro

Inicio

   escreva("Informe qualquer número: ")
   leia(num)
   
      se num < 0 entao
         escreval("Este número é negativo! :D")
      senao
           escreval("Este número é positivo! :D")
      fimSe

Fimalgoritmo