Algoritmo "Média15a100"

// Descrição   : Faça um algoritmo que calcule e escreva a média
//aritmética dos números inteiros entre 15 (inclusive) e 100 (inclusive)
// Autor(a)    : Ester Trindade
// Data atual  : 22/05/2024

Var

   soma : real
   i : inteiro

Inicio

      para i de 15 ate 100 passo 1 faca
           soma <- soma + i
      fimPara
      
      escreval("A média é: ", soma/85)


Fimalgoritmo