Algoritmo "11. EXERCÍCIO"

// Descrição   : Leia um vetor de 10 posições e verifique se existem
//valores iguais e os escreva
// Autor(a)    : Ester Trindade
// Data atual  : 03/06/2024

Var

   vet : vetor[0..9] de inteiro
   i, j : inteiro

Inicio


   para i de 0 ate 9 passo 1 faca
        escreva(i + 1, "º número:")
        leia(vet[i])
        

        
   fimPara

   escreval("Números repetitivos: ")
   

Fimalgoritmo
